# Just the Docs Theme Configuration
remote_theme: just-the-docs/just-the-docs

# Site settings
title: ftransfer Documentation
description: Secure file transfer over Tailscale networks with end-to-end encryption
url: "https://proudsunburn.github.io"
baseurl: "/ftransfer"
repository: "proudsunburn/ftransfer"

# Theme settings
color_scheme: dark
search_enabled: true
heading_anchors: true

# Navigation
nav_sort: case_insensitive
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/proudsunburn/ftransfer

# Mermaid diagrams support
mermaid:
  version: "10.6.1"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  mermaid: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.py"
  - "requirements.txt"
  - "venv/"
  - ".git/"
  - ".gitignore"
  - ".venv/"
  - "_site/"

# GitHub Pages
github:
  is_project_page: true
  repository_name: "ftransfer"
  owner_name: "proudsunburn"

# SEO
lang: en_US
author: "proudsunburn"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer
footer_content: 'Copyright &copy; 2024. Theme by <a href="https://github.com/just-the-docs/just-the-docs">Just the Docs</a>.'
