source "https://rubygems.org"

# GitHub Pages
gem "github-pages", "~> 228", group: :jekyll_plugins

# Just the Docs theme
gem "just-the-docs"

# Required dependencies
gem 'csv'
gem 'base64'
gem 'bigdecimal'
gem 'webrick'
